/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package co.tagtalk.winemate.thriftfiles;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum FeedType implements org.apache.thrift.TEnum {
  SYSTEMFEED(1),
  USERFEED(2),
  USERRATE(3);

  private final int value;

  private FeedType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static FeedType findByValue(int value) { 
    switch (value) {
      case 1:
        return SYSTEMFEED;
      case 2:
        return USERFEED;
      case 3:
        return USERRATE;
      default:
        return null;
    }
  }
}
