/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package co.tagtalk.winemate.thriftfiles;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.3)", date = "2017-02-24")
public class RatedBottlesResponse implements org.apache.thrift.TBase<RatedBottlesResponse, RatedBottlesResponse._Fields>, java.io.Serializable, Cloneable, Comparable<RatedBottlesResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RatedBottlesResponse");

  private static final org.apache.thrift.protocol.TField RATED_BOTTLE_HISTORY_FIELD_DESC = new org.apache.thrift.protocol.TField("ratedBottleHistory", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RatedBottlesResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RatedBottlesResponseTupleSchemeFactory());
  }

  public List<BottleInfo> ratedBottleHistory; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    RATED_BOTTLE_HISTORY((short)1, "ratedBottleHistory");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RATED_BOTTLE_HISTORY
          return RATED_BOTTLE_HISTORY;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RATED_BOTTLE_HISTORY, new org.apache.thrift.meta_data.FieldMetaData("ratedBottleHistory", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, BottleInfo.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RatedBottlesResponse.class, metaDataMap);
  }

  public RatedBottlesResponse() {
  }

  public RatedBottlesResponse(
    List<BottleInfo> ratedBottleHistory)
  {
    this();
    this.ratedBottleHistory = ratedBottleHistory;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RatedBottlesResponse(RatedBottlesResponse other) {
    if (other.isSetRatedBottleHistory()) {
      List<BottleInfo> __this__ratedBottleHistory = new ArrayList<BottleInfo>(other.ratedBottleHistory.size());
      for (BottleInfo other_element : other.ratedBottleHistory) {
        __this__ratedBottleHistory.add(new BottleInfo(other_element));
      }
      this.ratedBottleHistory = __this__ratedBottleHistory;
    }
  }

  public RatedBottlesResponse deepCopy() {
    return new RatedBottlesResponse(this);
  }

  @Override
  public void clear() {
    this.ratedBottleHistory = null;
  }

  public int getRatedBottleHistorySize() {
    return (this.ratedBottleHistory == null) ? 0 : this.ratedBottleHistory.size();
  }

  public java.util.Iterator<BottleInfo> getRatedBottleHistoryIterator() {
    return (this.ratedBottleHistory == null) ? null : this.ratedBottleHistory.iterator();
  }

  public void addToRatedBottleHistory(BottleInfo elem) {
    if (this.ratedBottleHistory == null) {
      this.ratedBottleHistory = new ArrayList<BottleInfo>();
    }
    this.ratedBottleHistory.add(elem);
  }

  public List<BottleInfo> getRatedBottleHistory() {
    return this.ratedBottleHistory;
  }

  public RatedBottlesResponse setRatedBottleHistory(List<BottleInfo> ratedBottleHistory) {
    this.ratedBottleHistory = ratedBottleHistory;
    return this;
  }

  public void unsetRatedBottleHistory() {
    this.ratedBottleHistory = null;
  }

  /** Returns true if field ratedBottleHistory is set (has been assigned a value) and false otherwise */
  public boolean isSetRatedBottleHistory() {
    return this.ratedBottleHistory != null;
  }

  public void setRatedBottleHistoryIsSet(boolean value) {
    if (!value) {
      this.ratedBottleHistory = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RATED_BOTTLE_HISTORY:
      if (value == null) {
        unsetRatedBottleHistory();
      } else {
        setRatedBottleHistory((List<BottleInfo>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RATED_BOTTLE_HISTORY:
      return getRatedBottleHistory();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RATED_BOTTLE_HISTORY:
      return isSetRatedBottleHistory();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RatedBottlesResponse)
      return this.equals((RatedBottlesResponse)that);
    return false;
  }

  public boolean equals(RatedBottlesResponse that) {
    if (that == null)
      return false;

    boolean this_present_ratedBottleHistory = true && this.isSetRatedBottleHistory();
    boolean that_present_ratedBottleHistory = true && that.isSetRatedBottleHistory();
    if (this_present_ratedBottleHistory || that_present_ratedBottleHistory) {
      if (!(this_present_ratedBottleHistory && that_present_ratedBottleHistory))
        return false;
      if (!this.ratedBottleHistory.equals(that.ratedBottleHistory))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_ratedBottleHistory = true && (isSetRatedBottleHistory());
    list.add(present_ratedBottleHistory);
    if (present_ratedBottleHistory)
      list.add(ratedBottleHistory);

    return list.hashCode();
  }

  @Override
  public int compareTo(RatedBottlesResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetRatedBottleHistory()).compareTo(other.isSetRatedBottleHistory());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRatedBottleHistory()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ratedBottleHistory, other.ratedBottleHistory);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RatedBottlesResponse(");
    boolean first = true;

    sb.append("ratedBottleHistory:");
    if (this.ratedBottleHistory == null) {
      sb.append("null");
    } else {
      sb.append(this.ratedBottleHistory);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RatedBottlesResponseStandardSchemeFactory implements SchemeFactory {
    public RatedBottlesResponseStandardScheme getScheme() {
      return new RatedBottlesResponseStandardScheme();
    }
  }

  private static class RatedBottlesResponseStandardScheme extends StandardScheme<RatedBottlesResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RatedBottlesResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RATED_BOTTLE_HISTORY
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list32 = iprot.readListBegin();
                struct.ratedBottleHistory = new ArrayList<BottleInfo>(_list32.size);
                BottleInfo _elem33;
                for (int _i34 = 0; _i34 < _list32.size; ++_i34)
                {
                  _elem33 = new BottleInfo();
                  _elem33.read(iprot);
                  struct.ratedBottleHistory.add(_elem33);
                }
                iprot.readListEnd();
              }
              struct.setRatedBottleHistoryIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RatedBottlesResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.ratedBottleHistory != null) {
        oprot.writeFieldBegin(RATED_BOTTLE_HISTORY_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.ratedBottleHistory.size()));
          for (BottleInfo _iter35 : struct.ratedBottleHistory)
          {
            _iter35.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RatedBottlesResponseTupleSchemeFactory implements SchemeFactory {
    public RatedBottlesResponseTupleScheme getScheme() {
      return new RatedBottlesResponseTupleScheme();
    }
  }

  private static class RatedBottlesResponseTupleScheme extends TupleScheme<RatedBottlesResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RatedBottlesResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetRatedBottleHistory()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetRatedBottleHistory()) {
        {
          oprot.writeI32(struct.ratedBottleHistory.size());
          for (BottleInfo _iter36 : struct.ratedBottleHistory)
          {
            _iter36.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RatedBottlesResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list37 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.ratedBottleHistory = new ArrayList<BottleInfo>(_list37.size);
          BottleInfo _elem38;
          for (int _i39 = 0; _i39 < _list37.size; ++_i39)
          {
            _elem38 = new BottleInfo();
            _elem38.read(iprot);
            struct.ratedBottleHistory.add(_elem38);
          }
        }
        struct.setRatedBottleHistoryIsSet(true);
      }
    }
  }

}

