/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package co.tagtalk.winemate.thriftfiles;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum UserActions implements org.apache.thrift.TEnum {
  ShareWineInfoToWechat(1),
  OpenedBottle(2),
  ShareWineryInfoToWechat(3),
  ShareWineryMemberShipToWechat(4);

  private final int value;

  private UserActions(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static UserActions findByValue(int value) { 
    switch (value) {
      case 1:
        return ShareWineInfoToWechat;
      case 2:
        return OpenedBottle;
      case 3:
        return ShareWineryInfoToWechat;
      case 4:
        return ShareWineryMemberShipToWechat;
      default:
        return null;
    }
  }
}
